language: python
python:
- '3.6'
- '3.7'
- '3.8'
- nightly
before_install:
- pip install -r requirements.txt
install:
- pip install .
script:
- pytest
deploy:
  provider: pypi
  username: __token__
  password:
    secure: Xu/kPu46Bs++RhtC7RT3DsUJy1o+30u6hoOQwrtqNVAXtgABCWkSJX7SRcRAx6Jr3oUkmAMB8YPrgqcGobpL8ReIvkcx3pVw8dDRDAMXMASBtYTb4FyVnvPWATDXc6J8xheeUhQ+lSOEDf6pyBu8+yKq7zrok1nIAKT6Q+t7MaJX1qh4t69QML9LfNicT2tATn+KNAGHq1mtHtH6rlhcjfCdQ2eaiFPzOx8xEXonRjiUIMtC8I5DCNeCOC5IKE9iXk57zkx7U1UEwIS7ifQeSId5Q8an0wybtGVhAPtjRlQABwdpH+nULDY1qLRjej3uWjkWHK3l5EN03jK7VDbgCFQtOBho00dHe6cETFH+XsIPHY4cUzIw3fN4yYXtXkr6eOmvEILjSezRGGWx9s4OqN/MzFM20drvsBx+mlWja8RtFdfZHqk7y8cA+WX6zvL2GyShntoS92nTYBIVtl5Tjom3EOhiu4RoP9iIUydp7Slk0J1njs6EpHqVDo4+q5UPRvfaMOJgvE7T7kdacCTG2UDXh4upfe+UJhsbePLIxaKxtt5iXEXGybmw8F3C5WoX37WUQPi9WY1U8Xbmdt3kDik67T4qureRXCDffkabEnZun3ju9Tx2gTnR6y3QwL1C4GBtLhPr4TYNoh71wOKaMxqWdgneTs20wadvkJbdZ6w=
  distributions: sdist bdist_wheel
  skip_existing: true
  on:
    tags: true
