language: python
python:
- '3.6'
- '3.7'
- '3.8'
- nightly
before_install:
- pip install -r requirements.txt
install:
- pip install .
script:
- pytest
deploy:
  provider: pypi
  user: pyows-travis-deploy
  password:
    secure: Wf9uU8XQI2LaZYlbhfJ9Bbso3a01b8n4bacTXESEL1GqkaKMzQrgIluFPOolPH5q1t9b5YvnZhHmtJLezyAenVA1hzakuWFXqg+QVlAPknfSbDzGlij3MdjOdhL9TWngkMp0zXnaQyWoZ1ENiGkQnohIkzNKHJQORCpt9EedeMXKUkyOd6Czm02P+wn0J4AJ+QGKmaU12pgzVjRGljR47WaXfyq7DFk/Uv9qyNfIM1rgueNXkW7JxPV2Z+xNUXlcijUmlhDXAKwFjc62XQTeM03JlgrlTzmFmhmT9wKTxNg8ZQoWbUo10CEFT68GlB75Bo5IhqdCSN95YJ+RpmqZs0YD9HbvGrbMAQN0DbHL51jNDE/gQSx8Ho2sqnuWql1ysG2iR286y6mRgdHFEJPOumt8eTeCtJ8/PhCo3cop7MFAd7+4ciNp6F/IHXxLgK3FvaCkWyPB0pH9e359szE98teOQFAtAr6iD2twYX6237jITYzTUwe9fntJwb9jn/nNl+1cJAb/NPVuOHaB7ueGnO/+Zm55RKh+01Kugs6Yj41tVdgqLkRFuoQhPcx1GiN29eZRrb99/jr6M0PfhA0ZA2M+NX37OY2oxbV35m7XLw7bwvz/EDR1Qhfew44eUJWABoRuxTCSjXDtt2YfWQHqwLXBc8kAoIQ0uShHE5NL+vg=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: EOxServer/pyows
